name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

# Questo deve corrispondere al profilo creato durante il setup
profile: 'default' 

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Qui decidiamo come salvare i dati su BigQuery
models:
  jaffle_shop:
    +materialized: table  # Tutto quello che creiamo sarà una TABELLA
    example:
      +materialized: view   # Le cose nella cartella 'example' saranno VISTE